### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rmros** [yarax/swagger-to-graphql#132]
{ SyntaxError: Error resolving $ref pointer "/home/ramin/Desktop/irsha/irsh-back/swagger.json#/definitions/invoices". 
Token "invoices" does not exist.
    at Pointer.resolve (/home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/pointer.js:87:17)
    at $Ref.resolve (/home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/ref.js:83:18)
    at $Refs._resolve (/home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/refs.js:155:15)
    at inventory$Ref (/home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/bundle.js:98:23)
    at /home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/bundle.js:73:11
    at Array.forEach (<anonymous>)
    at crawl (/home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/bundle.js:67:12)
    at /home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/bundle.js:76:11
    at Array.forEach (<anonymous>)
    at crawl (/home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/bundle.js:67:12)
    at /home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/bundle.js:76:11
    at Array.forEach (<anonymous>)
    at crawl (/home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/bundle.js:67:12)
    at /home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/bundle.js:76:11
    at Array.forEach (<anonymous>)
    at crawl (/home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/bundle.js:67:12)
    at /home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/bundle.js:76:11
    at Array.forEach (<anonymous>)
    at crawl (/home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/bundle.js:67:12)
    at /home/ramin/.nvm/versions/node/v11.9.0/lib/node_modules/swagger-to-graphql/node_modules/json-schema-ref-parser/lib/bundle.js:76:11
    at Array.forEach (<anonymous>)
  toJSON: [Function: errorToJSON],
  inspect: [Function: errorToString] }

**Comment by yarax** [comment]
So it just tells that there is a broken reference to `invoices` model in your schema
