### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by samgranger** [yarax/swagger-to-graphql#33]
With larger files, swagger-to-graphql seems to reach the max stack size.

> (node:29124) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RangeError: Maximum call stack size exceeded
(node:29124) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by samgranger** [comment]
More details:

 RangeError: Maximum call stack size exceeded
    at /usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:93:81
    at /usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:13379:38
    at /usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:3001:24)
    at Function.mapValues (/usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:13378:7)
    at getTypeFields (/usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:93:33)
    at createGQLObject (/usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:88:13)
    at jsonSchemaTypeToGraphQL (/usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:111:12)
    at /usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:96:13
    at /usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:13379:38
    at /usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:3001:24)
    at Function.mapValues (/usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:13378:7)
    at getTypeFields (/usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:93:33)
    at createGQLObject (/usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:88:13)
    at jsonSchemaTypeToGraphQL (/usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:111:12)
    at /usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:96:13
    at /usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:13379:38
    at /usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:3001:24)
    at Function.mapValues (/usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:13378:7)
    at getTypeFields (/usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:93:33)

**Comment by samgranger** [comment]
An example swagger for debugging: http://devdocs.magento.com/swagger/schemas/latest-2.1.schema.json

I believe it is caused by json-schema-ref-parser

**Comment by yarax** [comment]
Hi! Thanks for the issue, perhaps there is a recursion due to specific structure of the schema, I'll take a look

**Comment by KrzysztofKarol** [comment]
It's because of circular

```javascript
{
  "swagger": "2.0",
  "info": {
    "version": "2.1",
    "title": "Magento Enterprise Edition 2.1"
  },
  "...": "...",
  "definitions": {
    "...": "...",
    "sales-data-order-item-interface": {
      "type": "object",
      "description": "Order item interface. An order is a document that a web store issues to a customer. Magento generates a sales order that lists the product items, billing and shipping addresses, and shipping and payment methods. A corresponding external document, known as a purchase order, is emailed to the customer.",
      "properties": {
        "...": "...",
        "parent_item": {
          "$ref": "#/definitions/sales-data-order-item-interface"
        }
      },
      "required": ["sku"]
    }
  }
}
```

Circular dependency detector is required.

**Comment by KrzysztofKarol** [comment]
As @samgranger said json-schema-ref-parser returns "infinite" object
https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/docs/README.md#circular-refs

**Comment by aspirisen** [comment]
+1 Have the same

**Comment by jaakko-solita** [comment]
+1 me too

**Comment by gustaflindqvist** [comment]
@yarax Did you look into this bug? Any update?

**Comment by mihaislobozeanu** [comment]
Indeed, the PR is now [#44](https://github.com/yarax/swagger-to-graphql/pull/44) with all the indent issues solved (at least I hope so)

**Comment by ofersadgat** [comment]
For what its worth, I tried PR #44 and it didnt fix the circular reference issue for me, so I put up PR #54 which does fix it.
