### ISSUE TITLE
Error generating graphql 

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [yarax/swagger-to-graphql#4]
When I use custom headers the tool fails to create the GraphQL schema

```
Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "X-SitTEST-Proposition" does not.
    at invariant (~/swagger-to-graphql/node_modules/graphql/jsutils/invariant.js:19:11)
    at assertValidName (~/swagger-to-graphql/node_modules/graphql/utilities/assertValidName.js:28:27)
    at ~/swagger-to-graphql/node_modules/graphql/type/definition.js:287:46
    at Array.map (native)
    at ~/swagger-to-graphql/node_modules/graphql/type/definition.js:286:44
    at Array.forEach (native)
    at defineFieldMap (~/swagger-to-graphql/node_modules/graphql/type/definition.js:272:14)
    at GraphQLObjectType.getFields (~/swagger-to-graphql/node_modules/graphql/type/definition.js:235:44)
    at ~/swagger-to-graphql/node_modules/graphql/type/schema.js:207:27
    at typeMapReducer (~/swagger-to-graphql/node_modules/graphql/type/schema.js:219:7)
    at ~/swagger-to-graphql/node_modules/graphql/type/schema.js:217:22
    at Array.forEach (native)
    at ~/swagger-to-graphql/node_modules/graphql/type/schema.js:208:29
    at typeMapReducer (~/swagger-to-graphql/node_modules/graphql/type/schema.js:219:7)
    at Array.reduce (native)
    at new GraphQLSchema (~/swagger-to-graphql/node_modules/graphql/type/schema.js:95:34)
    at loadSchema.then.swaggerSchema (~/swagger-to-graphql/lib/index.js:40:12)
    at run (/usr/local/lib/node_modules/babel-cli/node_modules/core-js/modules/es6.promise.js:87:22)
    at /usr/local/lib/node_modules/babel-cli/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/babel-cli/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by yarax** [comment]
It's a bit weird, because GraphQL types are based on swagger paths. Could you also show your swagger schema?

**Comment by Ashraf-Ali-aa** [comment]
@yarax I have modified the default swagger schema to reproduce the issue if you look at line `47`, `55` etc if I remove the hyphen it works.

if you change regex `/^[_a-zA-Z][_a-zA-Z0-9]*$/` to `/^[_a-zA-Z][_a-zA-Z-0-9]*$/` it should work.

https://gist.github.com/Ashraf-Ali-aa/636716f40c4aa911f864fed3aee2e44e

**Comment by yarax** [comment]
Yes, GraphQL does not allow odd characters neither in type names not in parameters. I think it's unlikely, that `graphql-js` maintainers accept changes in regexp. Probably adding some optional parameters names mapping to `swagger-to-graphql` fits more here.

**Comment by Ashraf-Ali-aa** [comment]
@yarax ok thanks, would it also possible to add an export feature for the GraphQL Schema?

**Comment by yarax** [comment]
`swagger-to-graphql` itself a function accepting path to your swagger schema and returning promise with GraphQL schema
```
var graphQLSchema = require('swagger-to-graphql');
graphQLSchema('./test/fixtures/petstore.json').then(schema => {
```
