### ISSUE TITLE
RequestError: Error: Invalid URI "undefined/store/inventory"

### ISSUE THREAD

**Issue by 4F2E4A2E** [yarax/swagger-to-graphql#48]
Hi there! On my road trying to get [swagger-to-graphql working with another graphql-server other then graphql-express](https://gist.github.com/4F2E4A2E/d8da9003f561762a6b4631efbeb2e5e1), i get the following error when trying to fire up this query:

**swagger-to-graphql.yoga.js**:
```node
const {GraphQLServer} = require('graphql-yoga');
const swaggerGraphQLSchema = require('swagger-to-graphql');
const API_BASE_URL = 'http://petstore.swagger.io/v2';

swaggerGraphQLSchema('http://petstore.swagger.io/v2/swagger.json')
    .then(schema => {
        const options = {
            port: 4000,
            context: {
                GQLProxyBaseUrl: API_BASE_URL
            }
        };
        const server = new GraphQLServer({
            schema: schema
        });
        server.start(options, () => console.log('Server is running on localhost:' + options.port))
    })
    .catch(e => {
        throw e;
    });
```

**result screenshot**: 

![image](https://user-images.githubusercontent.com/64590/35470544-d1036f24-034b-11e8-8113-efe10c7e8956.png)

*Query*
```graphql
{
  viewer {
    getInventory {
      empty
    }
  }
}
```
*Error*
```node
"node.exe" swagger-to-graphql.yoga.js
Server is running on localhost:4000
RequestError: Error: Invalid URI "undefined/store/inventory"
    at new RequestError (node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (node_modules\request\request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.init (node_modules\request\request.js:274:17)
    at Request.RP$initInterceptor [as init] (node_modules\request-promise-core\configure\request2.js:45:29)
    at new Request (node_modules\request\request.js:128:8)
    at request (node_modules\request\index.js:53:10)
    at _callee$ (node_modules\swagger-to-graphql\lib\index.js:89:51)
    at tryCatch (node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (node_modules\core-js\library\modules\_export.js:35:28)
    at node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12
    at node_modules\swagger-to-graphql\lib\index.js:104:19
    at field.resolve (node_modules\graphql-extensions\lib\index.js:119:77)
    at resolveFieldValueOrError (node_modules\graphql\execution\execute.js:544:18)
    at resolveField (node_modules\graphql\execution\execute.js:508:16)

```

**swagger-to-graphql** generates an object whith the GraphQLSchema which all context information can be passed in order to generate the resolver functions correctly. 
The schema object (working only since version 1.2.2) is being passed to yoga almost correctly, see the error.
My best guess is that the host url (`GQLProxyBaseUrl: API_BASE_URL`) is being resolved (meaning promise) from graphql-express but not from the graphql-apollo-server.

In my understanding it would be better to pass all required information to swagger-to-graphql before it's schema generation, so that all queries can be resolved independently from the graphql server as intended. 

@yarax what do you say? What am i missing? Any quickfix for this? Do you have something in mind for this?

Also related to #46

**Comment by yarax** [comment]
Hi,
According to graphql-yoga, `context` must be passed to GraphQLServer constructor https://github.com/graphcool/graphql-yoga#graphqlserver

**Comment by 4F2E4A2E** [comment]
Thanks a lot @yarax , it's working fine now, on apollo-server and yoga:

**apollo-server:**
```
const express = require('express');
const bodyParser = require('body-parser');
const {graphqlExpress, graphiqlExpress} = require('apollo-server-express');
const graphQLSchema = require('swagger-to-graphql');
const API_BASE_URL = 'http://petstore.swagger.io/v2';

const app = express();
graphQLSchema('./schema/petstore.swagger.json')
    .then(schema => {
        app.use('/graphql', bodyParser.json(), graphqlExpress(() => {
            return {
                schema,
                context: {
                    GQLProxyBaseUrl: API_BASE_URL
                },
                pretty: true,
                graphiql: true
            };
        }));

        app.use('/graphiql', graphiqlExpress({endpointURL: '/graphql'}));
        app.listen(4000, () => console.log('Now browse to localhost:4000/graphiql'));
    })
    .catch(e => {
        throw e;
    });

```

**yoga:** 
```
const {GraphQLServer} = require('graphql-yoga');
const swaggerGraphQLSchema = require('swagger-to-graphql');
const API_BASE_URL = 'http://petstore.swagger.io/v2';

swaggerGraphQLSchema('./schema/petstore.swagger.json')
    .then(schema => {
        const options = {
            port: 4000
        };
        const server = new GraphQLServer({
            schema,
            context: {
                GQLProxyBaseUrl: API_BASE_URL
            }
        });
        server.start(options, () => console.log('Server is running on localhost:' + options.port))
    })
    .catch(e => {
        throw e;
    });
```
