### ISSUE TITLE
error running on same port

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [yarax/swagger-to-graphql#5]
if you start the GraphQl server then try to reopen the server again on the same port it displays an error message it should warn you about the server is already is running and you should be able to stop the server. 
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3009
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:65:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:84:10)
```

**Comment by yarax** [comment]
`app.js` is just an example of usage. You should not fork the library to have. Just install `swagger-to-graphql` as npm dependency and use it shown in the example
