### ISSUE TITLE
Getting a RangeError: Maximum call stack size exceeded     

### ISSUE THREAD

**Issue by aminesig** [yarax/swagger-to-graphql#51]
When I try to start a server with a rather big swagger file, the application throws this error
RangeError: Maximum call stack size exceeded
    at isPrototype (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/lodash/lodash.js:6415:25)
    at baseKeys (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/lodash/lodash.js:3494:12)
    at keys (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/lodash/lodash.js:13285:60)
    at /Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/lodash/lodash.js:4939:21
    at baseForOwn (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/lodash/lodash.js:3001:24)
    at Function.mapValues (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/lodash/lodash.js:13378:7)
    at getTypeFields (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/swagger-to-graphql/lib/typeMap.js:107:33)
    at createGQLObject (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/swagger-to-graphql/lib/typeMap.js:91:16)
    at jsonSchemaTypeToGraphQL (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/swagger-to-graphql/lib/typeMap.js:125:12)
    at /Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/swagger-to-graphql/lib/typeMap.js:110:13
    at /Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/lodash/lodash.js:13379:38
    at /Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/lodash/lodash.js:3001:24)
    at Function.mapValues (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/lodash/lodash.js:13378:7)
    at getTypeFields (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/swagger-to-graphql/lib/typeMap.js:107:33)
    at createGQLObject (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/swagger-to-graphql/lib/typeMap.js:91:16)
    at jsonSchemaTypeToGraphQL (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/swagger-to-graphql/lib/typeMap.js:125:12)
    at /Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/swagger-to-graphql/lib/typeMap.js:110:13
    at /Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/lodash/lodash.js:13379:38
    at /Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/lodash/lodash.js:3001:24)
    at Function.mapValues (/Users/macuser/Documents/Apps/server/swagger2grahpql/node_modules/lodash/lodash.js:13378:7)

**Comment by aminesig** [comment]
this is the file I tried to bootstrap with the server https://gist.github.com/aminesig/1d196a95e5811ab397e21c8642c5c6b9#file-usergrid-swagger-yaml
