### ISSUE TITLE
Error: Cannot build primitive type "Object"

### ISSUE THREAD

**Issue by rahulaga** [yarax/swagger-to-graphql#53]
I used the command line `swagger-to-graphql --swagger=./swagger.json > out.graphql`
I cannot share the swagger.json as it is internal APIs. I could share a snippet if you could point me to where the issue maybe. The swagger loads fine in the usual viewer. Thanks

Getting this error:
```
Error: Cannot build primitive type "Object"
    at getPrimitiveTypes (/usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:140:11)
    at jsonSchemaTypeToGraphQL (/usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:127:12)
    at /usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:110:13
    at /usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:13392:38
    at /usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:4917:15
    at baseForOwn (/usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:3002:24)
    at Function.mapValues (/usr/local/lib/node_modules/swagger-to-graphql/node_modules/lodash/lodash.js:13391:7)
    at getTypeFields (/usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:107:33)
    at createGQLObject (/usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:91:16)
    at createGQLObject (/usr/local/lib/node_modules/swagger-to-graphql/lib/typeMap.js:84:38)
    at /usr/local/lib/node_modules/swagger-to-graphql/lib/index.js:117:45
    at Array.reduce (<anonymous>)
    at getQueriesFields (/usr/local/lib/node_modules/swagger-to-graphql/lib/index.js:115:6)
    at fields (/usr/local/lib/node_modules/swagger-to-graphql/lib/index.js:46:33)
    at resolveThunk (/usr/local/lib/node_modules/swagger-to-graphql/node_modules/graphql/type/definition.js:304:40)
    at defineFieldMap (/usr/local/lib/node_modules/swagger-to-graphql/node_modules/graphql/type/definition.js:466:18)
    at GraphQLObjectType.getFields (/usr/local/lib/node_modules/swagger-to-graphql/node_modules/graphql/type/definition.js:440:44)
    at typeMapReducer (/usr/local/lib/node_modules/swagger-to-graphql/node_modules/graphql/type/schema.js:213:25)
    at /usr/local/lib/node_modules/swagger-to-graphql/node_modules/graphql/type/schema.js:223:20
    at Array.forEach (<anonymous>)
    at typeMapReducer (/usr/local/lib/node_modules/swagger-to-graphql/node_modules/graphql/type/schema.js:214:27)
    at Array.reduce (<anonymous>)

```

**Comment by 4F2E4A2E** [comment]
Please post an example of it containing the object definition in order to reproduce the error.

**Comment by yarax** [comment]
Hi @rahulaga,
this is because you are using Pascal case for naming types, but specification uses lowercase everywhere so the library supports only lowercase. 
In your case type should be "object"

**Comment by rahulaga** [comment]
thank you! I just renamed to "object" and it works!
