### ISSUE TITLE
Support of oneOf

### ISSUE THREAD

**Issue by yarax** [yarax/swagger-to-graphql#57]

**Comment by wh00527** [comment]
any progress? I got same issue, Don't know how to handle schema {"allOf".

**Comment by alfirin** [comment]
Same issue over here.

Did you have the time to look upon it?

Thanks

**Comment by tot-ra** [comment]
+1 can't convert schema with inheritance (`allOf`) :(
```
Error: RequestBody is formData, expected an object schema, got "{"allOf":[{"type":"object","properties":{
```
stacktrace..
```
 at Object.exports.getParamDetailsFromRequestBody ./node_modules/swagger-to-graphql/lib/swagger.js:122:19)
at ./node_modules/swagger-to-graphql/lib/swagger.js:177:27
at Array.forEach (<anonymous>)
at ./node_modules/swagger-to-graphql/lib/swagger.js:158:28
at Array.forEach (<anonymous>)
at Object.exports.getAllEndPoints (./node_modules/swagger-to-graphql/lib/swagger.js:156:31)
```

**Comment by constantinov** [comment]
+1 was not able to convert schema with allOf inheritance

**Comment by kargalskaya** [comment]
+1...

**Comment by vitorcamachoo** [comment]
+1

Any update ?

**Comment by 738** [comment]
+1

**Comment by evgenisokolov** [comment]
+ 1 allOf issue

**Comment by brian-ln** [comment]
The question here for allOf, oneOf, anyOf from the [OpenAPI spec](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) is how strict to be from a validation POV. The other question is if we want to use GraphQL Unions or just merge the objects into a meta-object.

**Comment by thees** [comment]
+1

**Comment by gablabelle** [comment]
Has some got a solution or a workaround ... We would like to automate the schema generation but we are currently writing our schema manually because of this. 😢

**Comment by henrikrudstrom** [comment]
+1

**Comment by gablabelle** [comment]
> Has some got a solution or a workaround ... We would like to automate the schema generation but we are currently writing our schema manually because of this. 😢

For those interested we are now using https://graphql-mesh.com/ in order to generate a schema file from our swagger files. Works like a charm.

**Comment by michaelremes** [comment]
+1
